### ISSUE TITLE
Updating to 4.0.1 stuck express session

### ISSUE THREAD

**Issue by RomanBurunkov** [gx0r/connect-session-knex#105]
I use connect-session-knex with passport-local-strategy.
Updating from 4.0.0 to 4.0.1 leads to issue when request stuck and has never reach next middleware.

Not sure why, but reverting back to 4.0.0 make it works again.

**Comment by silvertear** [comment]
I encountered something similarly when I upgraded from 4.0.0 -> 4.0.1 as well.  I'm working something that uses `passport-auth0` as the strategy and using connect-session-knex v4.0.1 causes an issue.  When logging in and entering in my credentials, the app hangs; and when I try to revisit the app (by reloading or something) it causes a duplicate key entry into the DB.

```
Uncaught DatabaseError error: with new_values (sid, expired, sess) as 
(  values ($1, $2::timestamp with time zone, $3::json)), 
upsert as (   update "sessions" cs set     sid = nv.sid,     expired = nv.expired,     sess = nv.sess   from new_values nv   where cs.sid = nv.sid   returning cs.* )
insert into "sessions" (sid, expired, sess) select sid, expired, sess 
from new_values where not exists (select 1 from upsert up where up.sid = new_values.sid) - duplicate key value violates unique constraint "sessions_pkey"
```

I'm guessing the changes from `4.0.0` to `4.0.1` where replacing bluebird introduced some sort of error.

**Comment by syxolk** [comment]
I noticed something similar in my app. I am using the following packages:
- `express` 4.19.2
- `knex` 3.1.0
- `passport` 0.6.0
- `passport-local` 1.0.0
- `connect-session-knex` - 4.1.0

Calling `req.login(user, callback)` seems to hang forever. When I reload the page I get the exact same error message as the other commenter above.

Downgrading to `connect-session-knex`4.0.0. fixed the issue.

**Comment by gx0r** [comment]
Ope. Pushed v4.0.2 that reverts dropping Bluebird.
