### ISSUE TITLE
Removing the Bluebird library

### ISSUE THREAD

**Issue by silvertear** [gx0r/connect-session-knex#106]
Since there was an issue going from `4.0.0` -> `4.0.1` due to the removal/replacement of the Bluebird library, I was looking into how to completely remove it without needing a replacement library.  I believe there is a way to do so using the native node functionality.

To start with, I would propose using `async` functions in order to handle and resolve the promises, as well as improving code readability.  The `async` functionality has been included in node since 7.6.0, so instead of relying on Bluebird and then-catch promise chaining, we could instead write the function using awaits and try-catches.  For example, we could potentially re-write the `KnexStore.prototype.get` call like this:

```
KnexStore.prototype.get = async function (sid, fn) {
	await this.ready;

	try {
		const condition = expiredCondition(this.knex);
		let response = await this.knex
			.select('sess')
			.from(this.tablename)
			.where(this.sidfieldname, '=', sid)
			.andWhereRaw(condition, dateAsISO(this.knex));

		let sessionVal;

		if (response[0]) {
			sessionVal = response[0].sess;
			if (typeof sessionVal === 'string') {
				sessionVal = JSON.parse(sessionVal);
			}
		}

		return fn(null, sessionVal);
	} catch(err){
		return fn(err);
	}
}
```

This could also simplify some of the other functions and make things more clear and easier to maintain going forward.  In addition, the [ExpressJS Session Store implementation definition](https://github.com/expressjs/session?tab=readme-ov-file#session-store-implementation) specify the callbacks and what they take, so invoking the callback with the exact values required would not have to depend on Bluebird `asCallback`.  

One other thing I'd propose is to increase the node engine specified in the `package.json` to `">=16"` as [`knex 3`](https://github.com/knex/knex/releases/tag/3.0.0) requires using a node version of 16 or greater as well.  Though I believe this would necessitate a major version increase.

@gx0r, would you possibly take these ideas into consideration for removing the Bluebird library?  Also, if you would rather, I would be happy to implement the above suggestions on a fork of this project and make a PR back into this one if you'd be ok with me making the changes.

**Comment by gx0r** [comment]
That sounds like a great approach and would be fantastic!

**Comment by gx0r** [comment]
Opened https://github.com/gx0r/connect-session-knex/pull/107
