### ISSUE TITLE
Library Creates Tables but Provides no (Documented) Way to Remove Them

### ISSUE THREAD

**Issue by machineghost** [gx0r/connect-session-knex#56]
I saw a reference to a `dbCleanup` function in one of the issues (I guess it wasn't working in SQLite?), but no other mention of what it is or how it works anywhere.

Beyond that, I also can't find any reference anywhere to a command to clear or remove the tables this library creates.

It's pretty standard practice in Knex to use Knex migrations to change the database, so it seems like this library really should have a way to generate a migration to add the table, rather than just adding them automatically within the app itself.

But separate from that, there absolutely should be some way to "tear down" the DB work done by the library (and that way should be documented).

**Comment by llambda** [comment]
I think I wrote this before knex had migrations. A MR would be welcome!
