### ISSUE TITLE
Add cockroach support

### ISSUE THREAD

**Issue by wodka** [gx0r/connect-session-knex#84]
right now the getPostgresFastQuery is broken for cockroach

https://github.com/gx0r/connect-session-knex/blob/master/lib/utils.js#L99

changing the line from
`    + '  values (?, ?::timestamp with time zone, ?::json)'`
to
`    + '  values (?::string, ?::timestamp with time zone, ?::json)'`

fixes this

**Comment by gx0r** [comment]
I would love to support this but I don't know if I can.

I'm just one person, and the amount of differences among databases (even major versions of the same database) has become untenable to maintain.

I might just recommend copy pasting the code into your project and tailoring it to your use case as needed, as trying to support everything is too much for me.
