### ISSUE TITLE
Knex v2.0.0?

### ISSUE THREAD

**Issue by plashenkov** [gx0r/connect-session-knex#99]
Hi there!

The new Knex 2.0.0 version was released recently. Would be nice to have connect-session-knex updated to the new Knex version. It looks like it is mostly backward compatible so maybe there's no changes required at all.

Thank you for the great library and good luck!

**Comment by gx0r** [comment]
Sounds good. 3.0.0 released.

**Comment by plashenkov** [comment]
Wow!! That sounds great too! Thank you! ;)
